name = "LibIIO"
uuid = "8d8c0393-7ec0-4e5b-ac5b-6c0bde4e6c57"
authors = ["iuliancioarca <iulian.cioarca@gmail.com>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.0"
