name = "LibIIO"
uuid = "8d8c0393-7ec0-4e5b-ac5b-6c0bde4e6c57"
authors = ["iuliancioarca <iulian.cioarca@gmail.com>"]
version = "0.1.0"

[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.0"
